CommunityHealth/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using CommunityHealth.Models;
using CommunityHealth.Models.ViewModels;
using CommunityHealth.ActionFilters;
using System.Data.Entity.Core;
using PagedList;

namespace CommunityHealth.Controllers
{
    public class EventController : Controller
    {
        private CommunityProgramsDBEntities db = new CommunityProgramsDBEntities();

        // GET: /Event/Index
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchKey, int? page)
        {
            // Save the current sorting parameter
            ViewBag.CurrentSort = sortOrder;
            // Extract sort order from the query string
            ViewBag.DateSort =sortOrder=="date" ? "date_d" : "date";
            //ViewBag.DepSort = sortOrder == "dep" ? "dep_d" : "dep";
            ViewBag.AddedBySort = sortOrder == "add" ? "add_d" : "add";
            //ViewBag.ProgramSort = sortOrder == "prog" ? "prog_d" : "prog";

            if(searchKey!=null)
            {
                page = 1;
            }
            else
            {
                searchKey = currentFilter;
            }
            ViewBag.CurrentFilter = searchKey;

            
            //  ********************************************
            //  Create an instance of the Data Handler class
            //  Pass the search paramaters to the Data Handler
            //  
            //
            //  ********************************************
            var communityactions = await db.CommunityActions
                .Include(c => c.Location)
                .Include(c => c.Program).ToListAsync();
            List<ActivityViewModel> activityViewModels = new List<ActivityViewModel>();
            foreach(var action in communityactions)
            {
                activityViewModels.Add(new ActivityViewModel
                {
                    communityAction = action,
                    junctionTypeActions = await db.JunctionTypeActions.Where(d => d.ActionID == action.ActionID).ToListAsync(),
                    junctionDepartmentActions = await db.JunctionDepartmentActions.Where(d => d.ActionID == action.ActionID).ToListAsync()
                });
            }
            if(!String.IsNullOrEmpty(searchKey))
            {
                string sKey = searchKey.ToLower();
                activityViewModels = activityViewModels.Where(s => (s.communityAction.BreifDescription != null && s.communityAction.BreifDescription.ToLower().Contains(searchKey)) 
                    ||(s.communityAction.Notes !=null && s.communityAction.Notes.ToLower().Contains(searchKey))).ToList();
            }

            // Case statement to determin sorting order
            switch(sortOrder)
            {
                case "date_d":
                    activityViewModels = activityViewModels.OrderByDescending(s => s.communityAction.StartDate).ToList();
                    break;
                case "date":
                    activityViewModels = activityViewModels.OrderBy(s => s.communityAction.StartDate).ToList();
                    break;
                case "add":
                    activityViewModels = activityViewModels.OrderBy(s => s.communityAction.AddedBy).ToList();
                    break;
                case "add_d":
                    activityViewModels = activityViewModels.OrderByDescending(s => s.communityAction.AddedBy).ToList();
                    break;
                /*case "prog":
                    activityViewModels = activityViewModels.OrderBy(s => s.communityAction.Program.ProgramName != null ? s.communityAction.Program.ProgramName: string.Empty).ToList();
                    break;
                case "prog_d":
                    activityViewModels = activityViewModels.OrderByDescending(s => s.communityAction.Program.ProgramName !=null).ToList();
                    break;*/
                default:
                    activityViewModels = activityViewModels.OrderByDescending(s => s.communityAction.ActionID).ToList();
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var pageOfResults = activityViewModels.ToPagedList(pageNumber,pageSize);
            return View(pageOfResults);
        }

        // Action for adding a new Type
        public ActionResult CreateNewType()
        {
            ViewBag.TyID = new SelectList(db.ActivityTypes, "TypeID", "TypeName");
            return PartialView("~/Views/Shared/EditorTemplates/JunctionTypeAction.cshtml", new JunctionTypeAction());
        }

        // Action for adding a new department via Ajax call
        public ActionResult CreateNewDepartment()
        {
            ViewBag.DepID = new SelectList(db.Departments, "DepartmentID", "DepartmentName");
            return PartialView("~/Views/Shared/EditorTemplates/JunctionDepartmentAction.cshtml", new JunctionDepartmentAction());
        }

        // GET: /Event/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityViewModel avModel = new ActivityViewModel();
            avModel.communityAction = await db.CommunityActions.FindAsync(id);
            avModel.junctionTypeActions = await db.JunctionTypeActions.Where(m => m.ActionID == avModel.communityAction.ActionID).ToListAsync();
            avModel.junctionDepartmentActions = await db.JunctionDepartmentActions.Where(m => m.ActionID == avModel.communityAction.ActionID).ToListAsync();
            if (avModel == null)
            {
                return HttpNotFound();
            }
            return View(avModel);
        }
        // GET: /Event/Create
        public ActionResult Create()
        {
            // Create lists of items for 
            SetViewBag();
            IList<RoleViewModel> roleViews = new List<RoleViewModel>();
            foreach(Role role in db.Roles)
            {
                roleViews.Add(new RoleViewModel()
                {
                    RoleName=role.RoleName,
                    RoleID = role.RoleID,
                    isSelected = false
                });
            }

            ActivityViewModel avModel = new ActivityViewModel
            {
                communityAction = new CommunityAction(),
                junctionTypeActions = new List<JunctionTypeAction>(),
                junctionDepartmentActions = new List<JunctionDepartmentAction>(),
                roleViewModels = roleViews
            };
            avModel.communityAction.AddedBy = User.Identity.Name;
            JunctionDepartmentAction jda = new JunctionDepartmentAction();
            JunctionTypeAction jta = new JunctionTypeAction();
            avModel.junctionDepartmentActions.Add(jda);
            avModel.junctionTypeActions.Add(jta);
            avModel.communityAction.StartDate = System.DateTime.Now;
            avModel.communityAction.EndDate = System.DateTime.Now;
            return View(avModel);
        }

        // POST: /Event/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ActivityViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                // Add the username to the AddedBy field
                newEvent.communityAction.AddedBy = User.Identity.Name;
                db.CommunityActions.Add(newEvent.communityAction);
                foreach(JunctionDepartmentAction jda in newEvent.junctionDepartmentActions)
                {
                    db.JunctionDepartmentActions.Add(jda);
                }
                foreach(JunctionTypeAction jta in newEvent.junctionTypeActions)
                {
                    db.JunctionTypeActions.Add(jta);
                }
                // Add the selected roles to the DBContext
                foreach(RoleViewModel rvm in newEvent.roleViewModels)
                {
                    if(rvm.isSelected)
                    {
                        db.JunctionRoleActions.Add(new JunctionRoleAction()
                        {
                            ActionID=newEvent.communityAction.ActionID,
                            RoleID=rvm.RoleID
                        });
                    }
                }
                // Add the selected populations to the DBContext if it isn't null

                foreach (int populationID in newEvent.selectedPopulations)
                {
                    db.JunctionPopulationActions.Add(new JunctionPopulationAction()
                    {
                        PopulationID = populationID,
                        ActionID = newEvent.communityAction.ActionID
                    });
                }
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            SetViewBag();
            return View(newEvent);
        }

        // GET: /Event/Edit/5
        [MyAuthorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Create the CommunityAction model to add to the view model.
            CommunityAction ca = await db.CommunityActions.FindAsync(id);
            if (ca == null)
            {
                return HttpNotFound();
            }
            ActivityViewModel activityviewmodel = new ActivityViewModel();
            activityviewmodel.communityAction = ca;
            // Get the Junction lists from the DBContext
            IList<JunctionRoleAction> junctionroleactions = await db.JunctionRoleActions.Where(d => d.ActionID == ca.ActionID).ToListAsync();

CommunityHealth/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CommunityHealth.Models;

namespace CommunityHealth.Controllers
{
    public class RoleController : Controller
    {
        private CommunityProgramsDBEntities db = new CommunityProgramsDBEntities();

        // GET: /Role/
        public async Task<ActionResult> Index()
        {
            return View(await db.Roles.ToListAsync());
        }

        // GET: /Role/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = await db.Roles.FindAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: /Role/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Role/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="RoleID,RoleName,isActive,RecordVersion")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.Roles.Add(role);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: /Role/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = await db.Roles.FindAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: /Role/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="RoleID,RoleName,isActive,RecordVersion")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        // GET: /Role/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = await db.Roles.FindAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: /Role/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Role role = await db.Roles.FindAsync(id);
            db.Roles.Remove(role);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CommunityHealth/Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CommunityHealth.Models;

namespace CommunityHealth.Controllers
{
    public class TypeController : Controller
    {
        private CommunityProgramsDBEntities db = new CommunityProgramsDBEntities();

        // GET: /Type/
        public async Task<ActionResult> Index()
        {
            return View(await db.ActivityTypes.ToListAsync());
        }

        // GET: /Type/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activitytype = await db.ActivityTypes.FindAsync(id);
            if (activitytype == null)
            {
                return HttpNotFound();
            }
            return View(activitytype);
        }

        // GET: /Type/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Type/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="TypeID,TypeName,isActive,RecordVersion")] ActivityType activitytype)
        {
            if (ModelState.IsValid)
            {
                db.ActivityTypes.Add(activitytype);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(activitytype);
        }

        // GET: /Type/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activitytype = await db.ActivityTypes.FindAsync(id);
            if (activitytype == null)
            {
                return HttpNotFound();
            }
            return View(activitytype);
        }

        // POST: /Type/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="TypeID,TypeName,isActive,RecordVersion")] ActivityType activitytype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activitytype).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(activitytype);
        }

        // GET: /Type/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activitytype = await db.ActivityTypes.FindAsync(id);
            if (activitytype == null)
            {
                return HttpNotFound();
            }
            return View(activitytype);
        }

        // POST: /Type/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ActivityType activitytype = await db.ActivityTypes.FindAsync(id);
            db.ActivityTypes.Remove(activitytype);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CommunityHealth/Views/Shared/EditorTemplates/Collection.cshtml
@using HtmlHelpers.BeginCollectionItem

<ul class="list-unstyled">
    @foreach (object item in Model)
    {
        <li style="padding-bottom:.5em;">
            @using (Html.BeginCollectionItem(Html.ViewData.TemplateInfo.HtmlFieldPrefix))
            {
                @Html.EditorFor(_ => item, null, "")
            }

        </li>
    }
</ul>

CommunityHealth/Views/Shared/EditorTemplates/CommunityAction.cshtml
@model CommunityHealth.Models.CommunityAction

<div class="form-horizontal">
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ActionID)
    @Html.HiddenFor(model => model.RecordVersion)
    <div class="row">
        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-4 required", id="lblSDate" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-4", id="lblEDate" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BreifDescription, new { @class = "control-label col-md-4 required" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.BreifDescription)
                @Html.ValidationMessageFor(model => model.BreifDescription)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "Location", new { @class = "control-label col-md-4 required"})
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.LocationID, ViewBag.LocID as SelectList,"--SELECT--", new { htmlAttributes = new { @class = "control-form ddlLocation"} })
            </div>
        </div>

        <div class="form-group divSubLocation">
            @Html.LabelFor(model => model.SubLocation, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.SubLocation)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramID, "Program", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.ProgramID, ViewBag.ProID as SelectList,"--SELECT--", new { htmlAttributes = new { @class = "control-form" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Notes)
                @Html.ValidationMessageFor(model => model.Notes)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Duration, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Duration)
                @Html.ValidationMessageFor(model => model.Duration)
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
        </div>
    </div>
</div>

CommunityHealth/Views/Shared/EditorTemplates/Date.cshtml
@model Nullable<DateTime>
@{
    DateTime dt = DateTime.Now;
    if (Model != null)
    {
        dt = (System.DateTime)Model;
    }
    @Html.TextBox("", String.Format("{0:d}", dt.ToShortDateString()), new { @class="datefield", type="date"})
}

CommunityHealth/Views/Shared/EditorTemplates/JunctionDepartmentAction.cshtml
@model CommunityHealth.Models.JunctionDepartmentAction

<div class="departmentList removeMe" id="@Model.IndexID">
    @using (Html.BeginCollectionItem("junctionDepartmentActions"))
    {
        <div>
            @Html.HiddenFor(model => model.IndexID)
            @Html.DropDownListFor(model => model.DepartmentID, ViewBag.DepID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "ddlDept", onchange = @"alert('Hi');" } })
            @Html.ValidationMessageFor(model => model.DepartmentID)
            <div style="display:none;">
                @Html.EditorFor(model => model.SubDepartment, "SubDepartment", new { @class = "control-label col-md-2 " })
            </div>
            <a href="#" class="deleteLink">delete</a>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/JunctionReportDepartment.cshtml
@model CommunityHealth.Models.JunctionReportDepartment

<div class="departmentList removeMe">
    @using (Html.BeginCollectionItem("junctionReportDepartments"))
    {
        <div>
            @Html.HiddenFor(model => model.IndexID)
            @Html.DropDownListFor(model => model.DepartmentID, ViewBag.DepID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "ddlDep" } })
            @Html.ValidationMessageFor(model => model.DepartmentID)
            <a href="#" class="deleteLink">delete</a>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/JunctionReportLocation.cshtml
@model CommunityHealth.Models.JunctionReportLocation

<div class="locationList removeMe" id="@Model.IndexID">
    @using (Html.BeginCollectionItem("junctionReportLocations"))
    {
        <div>
            @Html.HiddenFor(model => model.IndexID)
            @Html.DropDownListFor(model => model.LocationID, ViewBag.LocID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "ddlLoc" } })
            @Html.ValidationMessageFor(model => model.LocationID)
            <a href="#" class="deleteLink">delete</a>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/JunctionReportPopulation.cshtml
@model CommunityHealth.Models.JunctionReportPopulation

<div class="populationList removeMe" id="@Model.IndexID">
    @using (Html.BeginCollectionItem("junctionReportPopulations"))
    {
        <div>
            @Html.HiddenFor(model => model.IndexID)
            @Html.DropDownListFor(model => model.PopulationID, ViewBag.PopID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "ddlPop" } })
            @Html.ValidationMessageFor(model => model.PopulationID)
            <a href="#" class="deleteLink">delete</a>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/JunctionReportProgram.cshtml
@model CommunityHealth.Models.JunctionReportProgram

<div class="programList removeMe" id="@Model.IndexID">
    @using (Html.BeginCollectionItem("junctionReportPrograms"))
    {
        <div>
            @Html.HiddenFor(model => model.IndexID)
            @Html.DropDownListFor(model => model.ProgramID, ViewBag.ProID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "ddlPro" } })
            @Html.ValidationMessageFor(model => model.ProgramID)
            <a href="#" class="deleteLink">delete</a>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/JunctionReportRole.cshtml
@model CommunityHealth.Models.JunctionReportRole

<div class="roleList removeMe" id="@Model.IndexID">
    @using (Html.BeginCollectionItem("junctionReportRoles"))
    {
        <div>
            @Html.HiddenFor(model => model.IndexID)
            @Html.DropDownListFor(model => model.RoleID, ViewBag.RolID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "ddlRol" } })
            @Html.ValidationMessageFor(model => model.RoleID)
            <a href="#" class="deleteLink">delete</a>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/JunctionReportType.cshtml
@model CommunityHealth.Models.JunctionReportType
<div class="typeList removeMe" id="@Model.IndexID">
    @using (Html.BeginCollectionItem("junctionReportTypes"))
    {
        <div>
            @Html.HiddenFor(model => model.IndexID)
            @Html.DropDownListFor(model => model.TypeID, ViewBag.TypID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "ddlTyp", onchange = @"alert('Hi');" } })
            @Html.ValidationMessageFor(model => model.TypeID)
            <a href="#" class="deleteLink">delete</a>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/JunctionTypeAction.cshtml
@model CommunityHealth.Models.JunctionTypeAction
           
<div class="typeList removeMe" id="@Model.IndexID">
    @using (Html.BeginCollectionItem("junctionTypeActions"))
    {
        @Html.HiddenFor(model => model.ActionID)
        @Html.HiddenFor(model => model.IndexID)
        <div>
            <table>
                <tbody>
                    <tr>
                        <td>
                            <p>Type:</p>
                            @Html.DropDownListFor(model => model.TypeID, ViewBag.TyID as SelectList, "--SELECT--", new { htmlAttributes = new { @class = "control-form" } })
                            @Html.ValidationMessageFor(model => model.TypeID)
                        </td>
                        <td>
                            <p>Participants:</p>
                            @Html.EditorFor(model => model.Participants)
                        </td>
                        <td><a href="#" class="deleteLink">delete</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    }
</div>

CommunityHealth/Views/Shared/EditorTemplates/RoleViewModel.cshtml
@model CommunityHealth.Models.ViewModels.RoleViewModel


    <div>
        @Html.HiddenFor(model => model.RoleID)
        @Html.HiddenFor(model => model.RoleName)
        @Html.EditorFor(model => model.isSelected)
        @Html.DisplayFor(model => model.RoleName)
    </div>

CommunityHealth/Views/Shared/EditorTemplates/_AdminMenu.cshtml
<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Home", "Create", "Event")</li>
    <li>@Html.ActionLink("Departments", "Index", "Department")</li>
    <li>@Html.ActionLink("Locations", "Index", "Location")</li>
    <li>@Html.ActionLink("Populations", "Index", "Population")</li>
    <li>@Html.ActionLink("Programs", "Index", "Program")</li>
    <li>@Html.ActionLink("Roles", "Index", "Role")</li>
    <li>@Html.ActionLink("Activity Types", "Index", "Type")</li>
</ul>

CommunityHealth/Views/Shared/EditorTemplates/_PublicMenu.cshtml
<li>@Html.ActionLink("Home", "Create", "Event")</li>
<li>@Html.ActionLink("Home", "Activities List", "Event")</li>